<?php
/**
 * Definicion de secciones y campos del formulario de casos.
 * Generado a partir del analisis de form.xlsx (hoja 'survey').
 * Cada campo se guarda dentro de cases.form_data (JSON) salvo los
 * campos promovidos a columnas reales (ver Case::CORE_FIELDS).
 */
return [
    'informacion_general' => [
        'label' => '1. Información General del Incidente',
        'fields' => [
            [
                'name' => 'servicio',
                'label' => 'Servicio',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_servicio',
            ],
            [
                'name' => 'clase_de_servicio_1_incendios',
                'label' => 'Clase de Servicio 1. Incendios',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_clase_de_servicio_1_incendios',
            ],
            [
                'name' => 'clase_de_servicio_2_matpel',
                'label' => 'Clase de Servicio 2. Matpel',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_clase_de_servicio_2_matpel',
            ],
            [
                'name' => 'clase_de_servicio_3explosion',
                'label' => 'Clase de Servicio 3.Explosion',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_clase_de_servicio_3explosion',
            ],
            [
                'name' => 'clase_de_servicio_4rescates',
                'label' => 'Clase de Servicio 4.Rescates',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_clase_de_servicio_4rescates',
            ],
            [
                'name' => 'clase_de_servicio_5_fenomeno_de',
                'label' => 'Clase de Servicio 5. Fenomeno de Remocion de Masa',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_clase_de_servicio_5_fenomeno_de',
            ],
            [
                'name' => 'clase_de_servicio_6_inundacione',
                'label' => 'Clase de Servicio 6. Inundaciones',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_clase_de_servicio_6_inundacione',
            ],
            [
                'name' => 'clase_de_servicio_7_incidentes',
                'label' => 'Clase de Servicio 7. Incidentes con Arboles',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_clase_de_servicio_7_incidentes',
            ],
            [
                'name' => 'clase_de_servicio_8_falla_estru',
                'label' => 'Clase de Servicio 8. Falla Estructural',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_clase_de_servicio_8_falla_estru',
            ],
            [
                'name' => 'clase_de_servicio_10_falla_elec',
                'label' => 'Clase de Servicio 10. Falla Electrica',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_clase_de_servicio_10_falla_elec',
            ],
            [
                'name' => 'clase_de_servicio_11_atencion_p',
                'label' => 'Clase de Servicio 11. Atencion Preshopitalaria',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_clase_de_servicio_11_atencion_p',
            ],
            [
                'name' => 'clase_de_servicio_12quemas_proh',
                'label' => 'Clase de Servicio 12.Quemas Prohibidas',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_clase_de_servicio_12quemas_proh',
            ],
            [
                'name' => 'clase_de_servicio_14_reduccion',
                'label' => 'Clase de Servicio 14. Reduccion del Riesgo',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_clase_de_servicio_14_reduccion',
            ],
            [
                'name' => 'clase_de_servicio_15_caida_de_o',
                'label' => 'Clase de Servicio 15. Caida de Objetos',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_clase_de_servicio_15_caida_de_o',
            ],
            [
                'name' => 'numero_record',
                'label' => 'Numero Record',
                'hint' => '',
                'type' => 'integer',
                'list' => null,
            ],
            [
                'name' => 'fecha_del_incidente',
                'label' => 'Fecha del Incidente',
                'hint' => '',
                'type' => 'date',
                'list' => null,
            ],
            [
                'name' => 'hora_de_reporte',
                'label' => 'Hora de Reporte',
                'hint' => 'En esta casilla registrar la hora, en que la guardoa reporta el incidente a la tripulacion.&nbsp;',
                'type' => 'time',
                'list' => null,
            ],
            [
                'name' => 'hora_de_salida',
                'label' => 'Hora de Salida',
                'hint' => 'En esta casilla registrar la hora militar, en que el comandante de maquina informa el inicio de desplazamiento hacia el sitio del incidente',
                'type' => 'time',
                'list' => null,
            ],
            [
                'name' => 'hora_de_llegada',
                'label' => 'Hora de Llegada',
                'hint' => 'En esta casilla registrar la hora militar, en que el comandante de maquina informa la llegada al sitio del incidente.',
                'type' => 'time',
                'list' => null,
            ],
            [
                'name' => 'hora_de_cierre',
                'label' => 'Hora de cierre',
                'hint' => 'En esta casilla registrar la hora militar, en que el comandante de maquina informa la retirada del sitio del incidente',
                'type' => 'time',
                'list' => null,
            ],
            [
                'name' => 'hora_en_estaci_n',
                'label' => 'Hora en estación',
                'hint' => 'En esta casilla registrar la hora militar, en que el comandante de guardia recibe la llegada a la estación.',
                'type' => 'time',
                'list' => null,
            ],
            [
                'name' => 'field_349',
                'label' => 'Comandante del Incidente',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_field_349',
            ],
            [
                'name' => 'field_349_other',
                'label' => 'Otro',
                'hint' => '',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'direccion_del_incidente',
                'label' => 'Direccion del Incidente',
                'hint' => '',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'coordenadas',
                'label' => 'Coordenadas',
                'hint' => '',
                'type' => 'geopoint',
                'list' => null,
            ],
        ],
    ],
    'incendio_forestal' => [
        'label' => '2. Incendios / Zona Forestal / Causa',
        'fields' => [
            [
                'name' => '_rea_afectada',
                'label' => 'Área afectada',
                'hint' => 'Medida de la cobertura vegetal involucrada y dañada por el fuego, expresada en metros cuadrados.',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'zona_expuesta',
                'label' => 'Zona expuesta',
                'hint' => 'lugar geográfico donde esta ubica el incidente que pudo resultar afectada por la propagación del fuego si no se hubiese controlado.',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'tipo_de_vegetaci_n',
                'label' => 'Tipo de Vegetación',
                'hint' => 'Es el conjunto de plantas características que crecen en un determinado lugar: pastos, residuos vegetales, cercas vivas, vegetación nativa, plantación pina, plantación eucalipto, vegetación de páramo, vegetación de humedal, retamo espinoso. “Tomado de la clasificación de vegetación involucrada en incendios forestales en lo dispuesto por el ministerio de ambiente.”&nbsp;',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'etapa_de_desarrollo_del_fuego',
                'label' => 'Etapa de desarrollo del fuego',
                'hint' => 'Marcar con una X en la casilla correspondiente únicamente para el caso de la atención de un incendio y teniendo en cuenta las siguientes opciones:&nbsp;',
                'type' => 'select_one',
                'list' => 'list_etapa_de_desarrollo_del_fuego',
            ],
            [
                'name' => '_rea_o_punto_de_origen_del_ince',
                'label' => 'Área o punto de origen del Incendio o explosión',
                'hint' => 'En esta casilla se debe describir la estructura, parte de una estructura, o una localización geográfica general dentro del escenario de fuego, dentro de la cual, el punto de origen se puede localizar de manera razonable y o describir el punto de origen; el cual se define como la localización física exacta dentro del área de origen donde una fuente de calor y un combustible interactúan, dando como resultado un incendio o una explosión.',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'clasificacion_de_la_causa_para',
                'label' => 'Clasificacion de la Causa para Incendio o Explosion',
                'hint' => 'Marcar con una X en la casilla correspondiente únicamente para el caso de la atención de un incendio y teniendo en cuenta las siguientes opciones:',
                'type' => 'select_one',
                'list' => 'list_clasificacion_de_la_causa_para',
            ],
            [
                'name' => 'descripcion',
                'label' => 'Descripcion',
                'hint' => 'Realice un breve relato de la posible causa.',
                'type' => 'text',
                'list' => null,
            ],
        ],
    ],
    'acciones' => [
        'label' => '3. Descripción y Acciones Realizadas',
        'fields' => [
            [
                'name' => 'descripcion_',
                'label' => 'Descripcion',
                'hint' => 'Narre o describa los objetivos, estrategias y tácticas; pasos Sistema Comando de Incidente; decisiones y situaciones que considere relevantes durante la respuesta del incidente; continuidad del servicio, relevo del personal, etc. En caso de tener una novedad con personal, equipos, herramientas y accesorios, dé una breve descripción.',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'continue_con_la_descripcion',
                'label' => 'Continue con la Descripcion',
                'hint' => '',
                'type' => 'text',
                'list' => null,
            ],
        ],
    ],
    'personal_equipos' => [
        'label' => '4. Personal y Equipos (Jefe de Turno y Vehículos)',
        'fields' => [
            [
                'name' => 'jefe_de_turno',
                'label' => 'Jefe de Turno',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_jefe_de_turno',
            ],
            [
                'name' => 'jefe_de_turno_other',
                'label' => 'Otro',
                'hint' => '',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'vehiculos',
                'label' => 'Vehiculos',
                'hint' => '',
                'type' => 'select_multiple',
                'list' => 'list_vehiculos',
            ],
        ],
    ],
    'sci' => [
        'label' => '5. Formulario SCI (Sistema de Comando de Incidentes)',
        'fields' => [
            [
                'name' => 'nombre_del_incidente',
                'label' => 'Nombre del Incidente',
                'hint' => '',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'lugar_del_incidente',
                'label' => 'Lugar del Incidente',
                'hint' => '',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'fecha_y_hora_del_incidente',
                'label' => 'Fecha y hora del Incidente',
                'hint' => '',
                'type' => 'dateTime',
                'list' => null,
            ],
            [
                'name' => 'field_330',
                'label' => 'Comuna',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_field_330',
            ],
            [
                'name' => 'barrio_',
                'label' => 'Barrio',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_barrio_',
            ],
            [
                'name' => 'naturaleza_del_incidente',
                'label' => 'Naturaleza del Incidente',
                'hint' => 'Describa las características propias de cada evento. Comienzan a recolectarse en la evaluación inicial de la escena y en general, son los que responden a los siguientes interrogantes: » ¿Cuál es la naturaleza del incidente? » ¿Qué sucedió?',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'amenazas_del_incidente',
                'label' => 'Amenazas del Incidente',
                'hint' => 'Describa ¿Qué amenazas están presentes?',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'field_336',
                'label' => 'Area Afectada',
                'hint' => 'Describa ¿De qué tamaño es el área afectada? » ¿Cómo podría evolucionar?',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'aislamiento',
                'label' => 'Aislamiento',
                'hint' => 'Describa ¿Cómo se podría aislar el área?',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'objetivos',
                'label' => 'Objetivos',
                'hint' => 'Recuerde que los Objetivos deben ser claros y concisos y alcanzables. Se recomienda enumerar Cada Objetivo.',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'estretegias_y_tacticas',
                'label' => 'Estrategias y tacticas',
                'hint' => 'En el PAI se establecen la(s) estrategia(s) correspondientes a cada objetivo, asignaciones tácticas de los recursos con que cuenta y la organización. Estrategia se define como el medio por el cual alcanzamos los objetivos a través de la asignación del o de los recursos involucrados en las operaciones. Táctica se define como las acciones específicas que se deben realizar para lograr el resultado previsto en la estrategia y el logro del objetivo. Por ejemplo: mediante la técnica del llamado y escucha en el sector A, localizar posibles víctimas. Nota: Recuerde enumerar si la estrategia corresponde al objetivo 1 se enumera como 1.1 o si corresponde al objetivo 2 se enumera 2.1',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'ubicaci_n_del_puesto_de_comando',
                'label' => 'Ubicación del Puesto de Comando',
                'hint' => '',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => '_rea_de_espera',
                'label' => 'Área de Espera',
                'hint' => '',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'ruta_de_egreso',
                'label' => 'Ruta de Egreso',
                'hint' => '',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'mensaje_de_seguridad',
                'label' => 'Mensaje de Seguridad',
                'hint' => '',
                'type' => 'text',
                'list' => null,
            ],
        ],
    ],
    'finalizacion' => [
        'label' => '6. Evidencias y Responsable del Registro',
        'fields' => [
            [
                'name' => 'evidencia_1',
                'label' => 'Evidencia 1',
                'hint' => '',
                'type' => 'image',
                'list' => null,
            ],
            [
                'name' => 'evidencia_2',
                'label' => 'Evidencia 2',
                'hint' => '',
                'type' => 'image',
                'list' => null,
            ],
            [
                'name' => 'evidencia_3',
                'label' => 'Evidencia 3',
                'hint' => '',
                'type' => 'image',
                'list' => null,
            ],
            [
                'name' => 'anexe_censo',
                'label' => 'Anexe Censo:',
                'hint' => '',
                'type' => 'file',
                'list' => null,
            ],
            [
                'name' => 'acepto',
                'label' => 'Acepto',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_acepto',
            ],
            [
                'name' => 'nombre_completo',
                'label' => 'Nombre Completo',
                'hint' => '',
                'type' => 'select_one',
                'list' => 'list_nombre_completo',
            ],
            [
                'name' => 'nombre_completo_other',
                'label' => 'Otro',
                'hint' => '',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'cedula_de_ciudadania',
                'label' => 'Cedula de Ciudadania',
                'hint' => '',
                'type' => 'text',
                'list' => null,
            ],
            [
                'name' => 'firma',
                'label' => 'Firma.',
                'hint' => 'Firme encima de la línea',
                'type' => 'image',
                'list' => null,
            ],
        ],
    ],
];
