<?php
return [
    'persona' => [
        [
            'name' => 'nombres_y_apellidos',
            'label' => 'Nombres y Apellidos',
            'hint' => '',
            'type' => 'text',
            'list' => null,
        ],
        [
            'name' => 'edad',
            'label' => 'Edad',
            'hint' => '',
            'type' => 'decimal',
            'list' => null,
        ],
        [
            'name' => 'sexo',
            'label' => 'Sexo',
            'hint' => '',
            'type' => 'select_one',
            'list' => 'list_sexo',
        ],
        [
            'name' => 'sexo_other',
            'label' => 'Otro',
            'hint' => '',
            'type' => 'text',
            'list' => null,
        ],
        [
            'name' => 'rescatado',
            'label' => 'Rescatado',
            'hint' => '',
            'type' => 'select_one',
            'list' => 'list_rescatado',
        ],
        [
            'name' => 'con_vida',
            'label' => 'Con Vida',
            'hint' => '',
            'type' => 'select_one',
            'list' => 'list_con_vida',
        ],
    ],
    'animal' => [
        [
            'name' => 'tipo_de_animal',
            'label' => 'Tipo de Animal',
            'hint' => '',
            'type' => 'text',
            'list' => null,
        ],
        [
            'name' => 'tama_o',
            'label' => 'Tamaño',
            'hint' => '',
            'type' => 'text',
            'list' => null,
        ],
        [
            'name' => 'field_267',
            'label' => 'Sexo',
            'hint' => '',
            'type' => 'select_one',
            'list' => 'list_field_267',
        ],
        [
            'name' => 'field_268',
            'label' => 'Rescatado',
            'hint' => '',
            'type' => 'select_multiple',
            'list' => 'list_field_268',
        ],
        [
            'name' => 'field_270',
            'label' => 'Con vida',
            'hint' => '',
            'type' => 'select_multiple',
            'list' => 'list_field_270',
        ],
    ],
    'edificacion' => [
        [
            'name' => 'field_39',
            'label' => 'Tipo de Propiedad',
            'hint' => '',
            'type' => 'select_one',
            'list' => 'list_field_39',
        ],
        [
            'name' => 'direccion',
            'label' => 'Direccion',
            'hint' => 'En esta casilla registrar dirección exacta (con número de bloque, interior, bodega, torre, casa apartamento) de la primera edificación afectada por el incidente. Donde no exista nomenclatura del predio se debe registrar las coordenadas con un quipo tecnológico, utilizando coordenadas planas (4.6345, -74.1315); No usar direcciones aproximadas.',
            'type' => 'text',
            'list' => null,
        ],
        [
            'name' => 'uso_de_la_edificaci_n',
            'label' => 'Uso de la edificación',
            'hint' => '',
            'type' => 'select_one',
            'list' => 'list_uso_de_la_edificaci_n',
        ],
        [
            'name' => 'uso_de_la_edificaci_n_other',
            'label' => 'Otro',
            'hint' => '',
            'type' => 'text',
            'list' => null,
        ],
        [
            'name' => 'niveles_superiores',
            'label' => 'Niveles Superiores',
            'hint' => 'En esta casilla registrar la cantidad de niveles superiores que tiene la edificación.&nbsp;',
            'type' => 'decimal',
            'list' => null,
        ],
        [
            'name' => 'niveles_inferiores',
            'label' => 'Niveles Inferiores',
            'hint' => 'En esta casilla registrar la cantidad de niveles inferiores que tiene la edificación',
            'type' => 'decimal',
            'list' => null,
        ],
        [
            'name' => 'barrio',
            'label' => 'Barrio',
            'hint' => 'En esta casilla registrar el barrio donde se presentó el incidente&nbsp;',
            'type' => 'select_one',
            'list' => 'list_barrio',
        ],
        [
            'name' => 'barrio_other',
            'label' => 'Otro',
            'hint' => '',
            'type' => 'text',
            'list' => null,
        ],
        [
            'name' => 'comuna',
            'label' => 'Comuna',
            'hint' => 'En esta casilla registrar la Comuna',
            'type' => 'select_one',
            'list' => 'list_comuna',
        ],
        [
            'name' => 'estrato',
            'label' => 'Estrato',
            'hint' => 'En esta casilla registrar el estrato&nbsp;',
            'type' => 'range',
            'list' => null,
        ],
        [
            'name' => 'tipo_de_propiedad',
            'label' => 'Tipo de Propiedad',
            'hint' => '',
            'type' => 'select_one',
            'list' => 'list_tipo_de_propiedad',
        ],
        [
            'name' => 'tipo_de_propiedad_other',
            'label' => 'Otro',
            'hint' => '',
            'type' => 'text',
            'list' => null,
        ],
        [
            'name' => 'nombre_del_arrendador',
            'label' => 'Nombre del Arrendador',
            'hint' => 'En esta casilla registrar el nombre completo del Arrendador de la primera edificación afectada por el incidente',
            'type' => 'text',
            'list' => null,
        ],
        [
            'name' => 'field_45',
            'label' => 'Telefono del Arrendador',
            'hint' => 'En esta casilla registrar el número telefónico del propietario de la primera edificación afectada por el incidente',
            'type' => 'text',
            'list' => null,
        ],
        [
            'name' => 'nombre_del_propietario',
            'label' => 'Nombre del Propietario',
            'hint' => 'En esta casilla registrar el nombre completo del propietario de la primera edificación afectada por el incidente',
            'type' => 'text',
            'list' => null,
        ],
        [
            'name' => 'telefono_del_propietario',
            'label' => 'Telefono del Propietario',
            'hint' => 'En esta casilla registrar el número telefónico del propietario de la primera edificación afectada por el incidente',
            'type' => 'decimal',
            'list' => null,
        ],
        [
            'name' => 'ocupante_o_conductor',
            'label' => 'Ocupante o conductor:',
            'hint' => 'En esta casilla registrar el nombre completo del ocupante En caso de tratarse de un incidente que involucre inicialmente un vehículo, registrar en esta casilla el nombre del conductor del vehículo.',
            'type' => 'text',
            'list' => null,
        ],
        [
            'name' => 'telefono',
            'label' => 'Telefono',
            'hint' => 'En esta casilla registrar el número telefónico En caso de tratarse de un incidente que involucre inicialmente un vehículo, registrar en esta casilla el número telefónico del propietario del vehículo.',
            'type' => 'decimal',
            'list' => null,
        ],
        [
            'name' => 'raz_n_social',
            'label' => 'Razón Social',
            'hint' => 'En esta casilla se debe registrar el nombre completo del nombre del conjunto residencia o nombre de la empresa afectada por el incidente. En caso de tratarse de un incidente que involucre inicialmente un vehículo y sea de propiedad de una empresa, registrar el nombre de la empresa.',
            'type' => 'text',
            'list' => null,
        ],
        [
            'name' => 'tipo_de_vehiculo',
            'label' => 'Tipo de Vehiculo',
            'hint' => '',
            'type' => 'select_one',
            'list' => 'list_tipo_de_vehiculo',
        ],
        [
            'name' => 'tipo_de_vehiculo_other',
            'label' => 'Otro',
            'hint' => '',
            'type' => 'text',
            'list' => null,
        ],
        [
            'name' => 'marca',
            'label' => 'Marca',
            'hint' => 'Esta información debe ser validada de la tarjeta de propiedad, de no contar con la tarjeta de propiedad, omitir la información que no se logre recoger.',
            'type' => 'text',
            'list' => null,
        ],
        [
            'name' => 'modelo',
            'label' => 'Modelo',
            'hint' => 'Esta información debe ser validada de la tarjeta de propiedad, de no contar con la tarjeta de propiedad, omitir la información que no se logre recoger.',
            'type' => 'text',
            'list' => null,
        ],
        [
            'name' => 'placa',
            'label' => 'Placa',
            'hint' => 'Esta información debe ser validada de la tarjeta de propiedad, de no contar con la tarjeta de propiedad, omitir la información que no se logre recoger.',
            'type' => 'text',
            'list' => null,
        ],
        [
            'name' => 'color',
            'label' => 'Color',
            'hint' => 'Esta información debe ser validada de la tarjeta de propiedad, de no contar con la tarjeta de propiedad, omitir la información que no se logre recoger.',
            'type' => 'text',
            'list' => null,
        ],
        [
            'name' => 'field_56',
            'label' => 'Servicio',
            'hint' => 'Esta información debe ser validada de la tarjeta de propiedad, de no contar con la tarjeta de propiedad, omitir la información que no se logre recoger.',
            'type' => 'text',
            'list' => null,
        ],
    ],
];
